---
- name: Install/Start LAMP Service
  hosts: all
  become: yes
  tasks:
    - name: Install Apache
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Install Required Dependencies (Amazon Linux/CentOS)
      package:
        name:
          - openssl
          - openssl-devel
        state: present
      when: ansible_os_family in ["RedHat", "Amazon"]

    - name: Import MySQL GPG Key (Amazon Linux/CentOS)
      rpm_key:
        state: present
        key: https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
      when: ansible_os_family in ["RedHat", "Amazon"]

    - name: Download the MySQL 5.7 Community Release RPM (Amazon Linux/CentOS)
      get_url:
        url: https://repo.mysql.com//mysql57-community-release-el7-11.noarch.rpm
        dest: /tmp/mysql57-community-release-el7-11.noarch.rpm
      when: ansible_os_family in ["RedHat", "Amazon"]

    - name: Install the MySQL 5.7 Community Release RPM (Amazon Linux/CentOS)
      yum:
        name: /tmp/mysql57-community-release-el7-11.noarch.rpm
        state: present
      when: ansible_os_family in ["RedHat", "Amazon"]

    - name: Install MySQL 5.7 (Amazon Linux/CentOS)
      package:
        name: "{{ mysql_package }}"
        state: present
      when: ansible_os_family in ["RedHat", "Amazon"]

    - name: Install MySQL on Ubuntu
      apt:
        name: "{{ mysql_package_ubuntu }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install PHP on Linux/Ubuntu
      package:
        name: "{{ php_package }}"
        state: present

    - name: Start Apache Service on Linux/Ubuntu
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: yes
    
    - name: Start mysql on Linux
      service:
        name: mysqld
        state: started
        enabled: yes
      when: ansible_os_family in ["RedHat", "Amazon"]





